#ifdef FILLMENUDVARS
#undef FILLMENUDVARS
#endif

#define FILLMENUDVARS     exec "exec menudvars/player/l/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/player/l/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/player/l/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/player/l/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/player/l/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/player/l/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/player/l/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/player/l/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/player/l/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/player/l/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/player/l/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt oitc "exec menudvars/player/l/oitc.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/player/l/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/player/l/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/player/l/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/player/l/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/player/l/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/player/l/war.cfg"



#define SETA_SCR_FALLDAMAGEMINHEIGHT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_fallDamageMinHeight_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_fallDamageMinHeight_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_fallDamageMinHeight_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_fallDamageMinHeight_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_fallDamageMinHeight_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_fallDamageMinHeight_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_fallDamageMinHeight_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_fallDamageMinHeight_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_fallDamageMinHeight_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_fallDamageMinHeight_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_fallDamageMinHeight_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_fallDamageMinHeight_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_fallDamageMinHeight_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_fallDamageMinHeight_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_fallDamageMinHeight_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_fallDamageMinHeight_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_fallDamageMinHeight_war _null"

#define SETA_SCR_FALLDAMAGEMAXHEIGHT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_fallDamageMaxHeight_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_fallDamageMaxHeight_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_fallDamageMaxHeight_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_fallDamageMaxHeight_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_fallDamageMaxHeight_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_fallDamageMaxHeight_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_fallDamageMaxHeight_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_fallDamageMaxHeight_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_fallDamageMaxHeight_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_fallDamageMaxHeight_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_fallDamageMaxHeight_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_fallDamageMaxHeight_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_fallDamageMaxHeight_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_fallDamageMaxHeight_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_fallDamageMaxHeight_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_fallDamageMaxHeight_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_fallDamageMaxHeight_war _null"

#define SETA_SCR_JUMP_HEIGHT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_jump_height_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_jump_height_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_jump_height_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_jump_height_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_jump_height_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_jump_height_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_jump_height_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_jump_height_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_jump_height_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_jump_height_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_jump_height_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_jump_height_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_jump_height_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_jump_height_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_jump_height_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_jump_height_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_jump_height_war _null"

#define SETA_SCR_JUMP_SLOWDOWN_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_jump_slowdown_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_jump_slowdown_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_jump_slowdown_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_jump_slowdown_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_jump_slowdown_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_jump_slowdown_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_jump_slowdown_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_jump_slowdown_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_jump_slowdown_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_jump_slowdown_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_jump_slowdown_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_jump_slowdown_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_jump_slowdown_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_jump_slowdown_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_jump_slowdown_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_jump_slowdown_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_jump_slowdown_enable_war _null"

#define SETA_SCR_GAME_ALLOW_KILLCAM \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_game_allow_killcam_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_game_allow_killcam_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_game_allow_killcam_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_game_allow_killcam_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_game_allow_killcam_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_game_allow_killcam_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_game_allow_killcam_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_game_allow_killcam_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_game_allow_killcam_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_game_allow_killcam_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_game_allow_killcam_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_game_allow_killcam_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_game_allow_killcam_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_game_allow_killcam_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_game_allow_killcam_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_game_allow_killcam_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_game_allow_killcam_war _null"

#define SETA_SCR_PLAYER_FORCERESPAWN \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_player_forcerespawn_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_player_forcerespawn_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_player_forcerespawn_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_player_forcerespawn_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_player_forcerespawn_dom _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_player_forcerespawn_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_player_forcerespawn_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_player_forcerespawn_koth _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_player_forcerespawn_sab _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_player_forcerespawn_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_player_forcerespawn_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_player_forcerespawn_war _null"

#define SETA_SCR_QUICKACTIONS_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_quickactions_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_quickactions_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_quickactions_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_quickactions_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_quickactions_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_quickactions_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_quickactions_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_quickactions_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_quickactions_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_quickactions_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_quickactions_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_quickactions_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_quickactions_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_quickactions_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_quickactions_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_quickactions_enable_war _null"

#define SETA_SCR_THIRDPERSON_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_thirdperson_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_thirdperson_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_thirdperson_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_thirdperson_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_thirdperson_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_thirdperson_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_thirdperson_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_thirdperson_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_thirdperson_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_thirdperson_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_thirdperson_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_thirdperson_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_thirdperson_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_thirdperson_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_thirdperson_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_thirdperson_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_thirdperson_enable_war _null"

#define SETA_SCR_PLAYER_LEAN_FIX \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_player_lean_fix_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_player_lean_fix_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_player_lean_fix_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_player_lean_fix_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_player_lean_fix_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_player_lean_fix_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_player_lean_fix_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_player_lean_fix_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_player_lean_fix_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_player_lean_fix_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_player_lean_fix_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_player_lean_fix_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_player_lean_fix_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_player_lean_fix_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_player_lean_fix_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_player_lean_fix_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_player_lean_fix_war _null"

#define SETA_SCR_BOB_EFFECT_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_bob_effect_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_bob_effect_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_bob_effect_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_bob_effect_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_bob_effect_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_bob_effect_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_bob_effect_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_bob_effect_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_bob_effect_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_bob_effect_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_bob_effect_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_bob_effect_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_bob_effect_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_bob_effect_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_bob_effect_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_bob_effect_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_bob_effect_enable_war _null"

#define SETA_SCR_CG_FOOTSTEPS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_cg_footsteps_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_cg_footsteps_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_cg_footsteps_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_cg_footsteps_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_cg_footsteps_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_cg_footsteps_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_cg_footsteps_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_cg_footsteps_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_cg_footsteps_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_cg_footsteps_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_cg_footsteps_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_cg_footsteps_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_cg_footsteps_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_cg_footsteps_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_cg_footsteps_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_cg_footsteps_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_cg_footsteps_war _null"

#define SETA_SCR_CAP_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_cap_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_cap_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_cap_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_cap_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_cap_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_cap_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_cap_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_cap_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_cap_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_cap_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_cap_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_cap_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_cap_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_cap_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_cap_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_cap_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_cap_enable_war _null"

#define SETA_SCR_CAP_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_cap_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_cap_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_cap_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_cap_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_cap_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_cap_time_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_cap_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_cap_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_cap_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_cap_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_cap_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_cap_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_cap_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_cap_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_cap_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_cap_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_cap_time_war _null"

#define SETA_SCR_CAP_TIME_ACTIVATED \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_cap_time_activated_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_cap_time_activated_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_cap_time_activated_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_cap_time_activated_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_cap_time_activated_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_cap_time_activated_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_cap_time_activated_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_cap_time_activated_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_cap_time_activated_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_cap_time_activated_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_cap_time_activated_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_cap_time_activated_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_cap_time_activated_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_cap_time_activated_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_cap_time_activated_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_cap_time_activated_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_cap_time_activated_war _null"

#define SETA_SCR_CAP_FIRSTSPAWN \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_cap_firstspawn_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_cap_firstspawn_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_cap_firstspawn_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_cap_firstspawn_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_cap_firstspawn_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_cap_firstspawn_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_cap_firstspawn_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_cap_firstspawn_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_cap_firstspawn_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_cap_firstspawn_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_cap_firstspawn_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_cap_firstspawn_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_cap_firstspawn_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_cap_firstspawn_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_cap_firstspawn_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_cap_firstspawn_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_cap_firstspawn_war _null"

#define SETA_SCR_DE_DROPWEAPON_ON_ARM_HIT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_dropweapon_on_arm_hit_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_dropweapon_on_arm_hit_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_dropweapon_on_arm_hit_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_dropweapon_on_arm_hit_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_dropweapon_on_arm_hit_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_dropweapon_on_arm_hit_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_dropweapon_on_arm_hit_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_dropweapon_on_arm_hit_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_dropweapon_on_arm_hit_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_dropweapon_on_arm_hit_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_dropweapon_on_arm_hit_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_dropweapon_on_arm_hit_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_dropweapon_on_arm_hit_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_dropweapon_on_arm_hit_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_dropweapon_on_arm_hit_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_dropweapon_on_arm_hit_war _null"

#define SETA_SCR_DE_DROPWEAPON_CHANCE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_dropweapon_chance_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_dropweapon_chance_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_dropweapon_chance_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_dropweapon_chance_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_dropweapon_chance_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_dropweapon_chance_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_dropweapon_chance_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_dropweapon_chance_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_dropweapon_chance_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_dropweapon_chance_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_dropweapon_chance_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_dropweapon_chance_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_dropweapon_chance_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_dropweapon_chance_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_dropweapon_chance_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_dropweapon_chance_war _null"

#define SETA_SCR_DE_FALLDOWN_ON_LEG_HIT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_falldown_on_leg_hit_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_falldown_on_leg_hit_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_falldown_on_leg_hit_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_falldown_on_leg_hit_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_falldown_on_leg_hit_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_falldown_on_leg_hit_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_falldown_on_leg_hit_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_falldown_on_leg_hit_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_falldown_on_leg_hit_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_falldown_on_leg_hit_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_falldown_on_leg_hit_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_falldown_on_leg_hit_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_falldown_on_leg_hit_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_falldown_on_leg_hit_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_falldown_on_leg_hit_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_falldown_on_leg_hit_war _null"

#define SETA_SCR_DE_FALLDOWN_CHANCE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_falldown_chance_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_falldown_chance_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_falldown_chance_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_falldown_chance_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_falldown_chance_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_falldown_chance_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_falldown_chance_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_falldown_chance_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_falldown_chance_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_falldown_chance_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_falldown_chance_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_falldown_chance_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_falldown_chance_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_falldown_chance_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_falldown_chance_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_falldown_chance_war _null"

#define SETA_SCR_DE_SHIFTVIEW_ON_DAMAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_shiftview_on_damage_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_shiftview_on_damage_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_shiftview_on_damage_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_shiftview_on_damage_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_shiftview_on_damage_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_shiftview_on_damage_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_shiftview_on_damage_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_shiftview_on_damage_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_shiftview_on_damage_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_shiftview_on_damage_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_shiftview_on_damage_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_shiftview_on_damage_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_shiftview_on_damage_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_shiftview_on_damage_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_shiftview_on_damage_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_shiftview_on_damage_war _null"

#define SETA_SCR_DE_BREAK_ANKLE_ON_FALL \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_break_ankle_on_fall_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_break_ankle_on_fall_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_break_ankle_on_fall_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_break_ankle_on_fall_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_break_ankle_on_fall_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_break_ankle_on_fall_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_break_ankle_on_fall_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_break_ankle_on_fall_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_break_ankle_on_fall_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_break_ankle_on_fall_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_break_ankle_on_fall_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_break_ankle_on_fall_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_break_ankle_on_fall_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_break_ankle_on_fall_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_break_ankle_on_fall_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_break_ankle_on_fall_war _null"

#define SETA_SCR_DE_SLOWDOWN_ON_LEG_HIT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_de_slowdown_on_leg_hit_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_de_slowdown_on_leg_hit_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_de_slowdown_on_leg_hit_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_de_slowdown_on_leg_hit_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_de_slowdown_on_leg_hit_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_de_slowdown_on_leg_hit_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_de_slowdown_on_leg_hit_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_de_slowdown_on_leg_hit_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_de_slowdown_on_leg_hit_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_de_slowdown_on_leg_hit_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_de_slowdown_on_leg_hit_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_de_slowdown_on_leg_hit_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_de_slowdown_on_leg_hit_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_de_slowdown_on_leg_hit_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_de_slowdown_on_leg_hit_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_de_slowdown_on_leg_hit_war _null"

