#define SETA_CUSTOM_VARS "seta ct_conChatHistOnly 0; seta ct_hud_show_inventory 0; seta ct_hud_show_scores 0; seta ct_hud_hardcore_show_compass 0; seta ct_chat_position standard; seta ct_scoreboardNew 0; seta r_normal 1; seta ct_unlocked_wpf 0; seta ct_unlocked_attach 0; seta ct_unlocked_camo 0; seta ct_lm_ver 18"
#define SETA_CUSTOM_VARS_EX "seta compassObjectiveScreen 0; seta player_breath_snd_src 0; seta snd_enableSrc 0; seta ct_unlocked_weap 0; seta ct_unlocked_attach 0; seta ct_unlocked_camo 0";
#define ASH1 "set con_outputWindowColor 0.1 0.2 1 0.2"
#define ASH2 "set con_outputSliderColor 0.2 0.7 0 0.6"
#define ASH3 "set con_inputBoxColor 0.4 0.5 0.8 1"
#define ASH4 "set con_inputHintBoxColor 0.4 0.6 0.8 1"
#define ASH5 "con_hidechannel *; con_showchannel client"
		
#define AHH1 "set con_outputWindowColor 0.35 0.35 0.3 0.75"
#define AHH2 "set con_outputSliderColor 0.15 0.15 0.1 0.6"
#define AHH3 "set con_inputBoxColor 0.25 0.25 0.2 1"
#define AHH4 "set con_inputHintBoxColor 0.4 0.4 0.35 1"
#define AHH5 "con_hidechannel *; con_showchannel dontfilter error gamenotify boldgame subtitle obituary logfile_only console_only gfx sound files devgui profile ui client server system playerweap ai anim physics fx leaderboards parserscript script"

#define ASN1 "seta cg_scoreboardHeight 480; seta cg_scoreboardItemHeight 15; seta cg_scoreboardBannerHeight 30"
#define ASO1 "seta cg_scoreboardHeight 435; seta cg_scoreboardItemHeight 18; seta cg_scoreboardBannerHeight 35"