//GREED
CHOICE_DVARFLOATLIST( 28, "@OW_GR_ACTIVE_DROP_ZONES", scr_gr_active_drop_zones, { "1" 1 "2" 2 "3" 3 }, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_GR_DROP_ZONES_RELOCATION_TIME", scr_gr_drop_zones_relocation_time, 4, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_GR_BASE_DOGTAG_SCORE", scr_gr_base_dogtag_score, 4, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_GR_DOGTAG_AUTOREMOVAL_TIME", scr_gr_dogtag_autoremoval_time, 4, ; )
CHOICE_DVARYESNO( 28, "@OW_GR_MINIMAP_MARK_RED_DROPS", scr_gr_minimap_mark_red_drops, ; )