#ifdef FILLMENUDVARS
#undef FILLMENUDVARS
#endif

#define FILLMENUDVARS     exec "exec menudvars/weapons/l/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/weapons/l/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/weapons/l/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/weapons/l/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/weapons/l/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/weapons/l/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/weapons/l/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/weapons/l/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/weapons/l/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/weapons/l/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/weapons/l/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/weapons/l/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/weapons/l/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/weapons/l/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/weapons/l/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/weapons/l/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/weapons/l/war.cfg"

#ifdef SAVEMENUDVARS
#undef SAVEMENUDVARS
#endif

#define SAVEMENUDVARS     execOnDvarStringValue menu_cfg_gt _def "exec menudvars/weapons/s/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/weapons/s/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/weapons/s/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/weapons/s/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/weapons/s/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/weapons/s/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/weapons/s/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/weapons/s/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/weapons/s/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/weapons/s/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/weapons/s/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/weapons/s/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/weapons/s/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/weapons/s/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/weapons/s/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/weapons/s/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/weapons/s/war.cfg"


#define SETA_SCR_GRENADE_ALLOW_COOKING \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_grenade_allow_cooking_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_grenade_allow_cooking_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_grenade_allow_cooking_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_grenade_allow_cooking_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_grenade_allow_cooking_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_grenade_allow_cooking_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_grenade_allow_cooking_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_grenade_allow_cooking_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_grenade_allow_cooking_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_grenade_allow_cooking_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_grenade_allow_cooking_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_grenade_allow_cooking_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_grenade_allow_cooking_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_grenade_allow_cooking_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_grenade_allow_cooking_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_grenade_allow_cooking_war _null"

#define SETA_SCR_BULLET_PENETRATION_ENABLED \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_bullet_penetration_enabled_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_bullet_penetration_enabled_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_bullet_penetration_enabled_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_bullet_penetration_enabled_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_bullet_penetration_enabled_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_bullet_penetration_enabled_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_bullet_penetration_enabled_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_bullet_penetration_enabled_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_bullet_penetration_enabled_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_bullet_penetration_enabled_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_bullet_penetration_enabled_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_bullet_penetration_enabled_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_bullet_penetration_enabled_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_bullet_penetration_enabled_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_bullet_penetration_enabled_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_bullet_penetration_enabled_war _null"

#define SETA_SCR_CONCUSSION_GRENADES_BASE_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_concussion_grenades_base_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_concussion_grenades_base_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_concussion_grenades_base_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_concussion_grenades_base_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_concussion_grenades_base_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_concussion_grenades_base_time_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_concussion_grenades_base_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_concussion_grenades_base_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_concussion_grenades_base_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_concussion_grenades_base_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_concussion_grenades_base_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_concussion_grenades_base_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_concussion_grenades_base_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_concussion_grenades_base_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_concussion_grenades_base_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_concussion_grenades_base_time_war _null"

#define SETA_SCR_DELETEEXPLOSIVESONSPAWN \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_deleteexplosivesonspawn_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_deleteexplosivesonspawn_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_deleteexplosivesonspawn_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_deleteexplosivesonspawn_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_deleteexplosivesonspawn_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_deleteexplosivesonspawn_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_deleteexplosivesonspawn_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_deleteexplosivesonspawn_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_deleteexplosivesonspawn_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_deleteexplosivesonspawn_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_deleteexplosivesonspawn_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_deleteexplosivesonspawn_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_deleteexplosivesonspawn_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_deleteexplosivesonspawn_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_deleteexplosivesonspawn_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_deleteexplosivesonspawn_war _null"

#define SETA_SCR_DELETEEXPLOSIVESONDEATH \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_deleteexplosivesondeath_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_deleteexplosivesondeath_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_deleteexplosivesondeath_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_deleteexplosivesondeath_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_deleteexplosivesondeath_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_deleteexplosivesondeath_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_deleteexplosivesondeath_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_deleteexplosivesondeath_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_deleteexplosivesondeath_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_deleteexplosivesondeath_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_deleteexplosivesondeath_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_deleteexplosivesondeath_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_deleteexplosivesondeath_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_deleteexplosivesondeath_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_deleteexplosivesondeath_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_deleteexplosivesondeath_war _null"

#define SETA_SCR_OBJECTIVE_SAFEZONE_ENABLE \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_objective_safezone_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_objective_safezone_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_objective_safezone_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_objective_safezone_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_objective_safezone_enable_sd _null"

#define SETA_SCR_OBJECTIVE_SAFEZONE_RADIUS \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_objective_safezone_radius_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_objective_safezone_radius_dom _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_objective_safezone_radius_koth _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_objective_safezone_radius_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_objective_safezone_radius_sd _null"

#define SETA_SCR_DELAY_FRAG_GRENADES \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_frag_grenades_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_frag_grenades_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_frag_grenades_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_frag_grenades_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_frag_grenades_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_frag_grenades_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_frag_grenades_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_frag_grenades_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_frag_grenades_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_frag_grenades_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_frag_grenades_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_frag_grenades_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_frag_grenades_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_frag_grenades_war _null"

#define SETA_SCR_DELAY_GRENADE_LAUNCHERS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_grenade_launchers_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_grenade_launchers_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_grenade_launchers_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_grenade_launchers_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_grenade_launchers_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_grenade_launchers_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_grenade_launchers_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_grenade_launchers_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_grenade_launchers_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_grenade_launchers_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_grenade_launchers_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_grenade_launchers_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_grenade_launchers_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_grenade_launchers_war _null"

#define SETA_SCR_DELAY_SMOKE_GRENADES \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_smoke_grenades_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_smoke_grenades_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_smoke_grenades_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_smoke_grenades_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_smoke_grenades_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_smoke_grenades_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_smoke_grenades_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_smoke_grenades_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_smoke_grenades_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_smoke_grenades_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_smoke_grenades_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_smoke_grenades_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_smoke_grenades_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_smoke_grenades_war _null"

#define SETA_SCR_DELAY_FLASH_GRENADES \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_flash_grenades_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_flash_grenades_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_flash_grenades_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_flash_grenades_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_flash_grenades_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_flash_grenades_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_flash_grenades_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_flash_grenades_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_flash_grenades_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_flash_grenades_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_flash_grenades_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_flash_grenades_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_flash_grenades_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_flash_grenades_war _null"

#define SETA_SCR_DELAY_CONCUSSION_GRENADES \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_concussion_grenades_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_concussion_grenades_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_concussion_grenades_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_concussion_grenades_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_concussion_grenades_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_concussion_grenades_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_concussion_grenades_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_concussion_grenades_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_concussion_grenades_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_concussion_grenades_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_concussion_grenades_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_concussion_grenades_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_concussion_grenades_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_concussion_grenades_war _null"

#define SETA_SCR_DELAY_RPGS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_rpgs_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_rpgs_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_rpgs_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_rpgs_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_rpgs_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_rpgs_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_rpgs_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_rpgs_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_rpgs_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_rpgs_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_rpgs_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_rpgs_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_rpgs_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_rpgs_war _null"

#define SETA_SCR_DELAY_C4S \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_c4s_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_c4s_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_c4s_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_c4s_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_c4s_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_c4s_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_c4s_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_c4s_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_c4s_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_c4s_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_c4s_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_c4s_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_c4s_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_c4s_war _null"

#define SETA_SCR_DELAY_CLAYMORES \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_claymores_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_claymores_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_claymores_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_claymores_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_claymores_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_claymores_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_claymores_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_claymores_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_claymores_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_claymores_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_claymores_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_claymores_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_claymores_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_claymores_war _null"

#define SETA_SCR_DELAY_ONLY_ROUND_START \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_only_round_start_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_only_round_start_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_only_round_start_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_only_round_start_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_only_round_start_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_only_round_start_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_only_round_start_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_only_round_start_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_only_round_start_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_only_round_start_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_only_round_start_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_only_round_start_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_only_round_start_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_only_round_start_war _null"

#define SETA_SCR_DELAY_SOUND_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_delay_sound_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_delay_sound_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_delay_sound_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_delay_sound_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_delay_sound_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_delay_sound_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_delay_sound_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_delay_sound_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_delay_sound_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_delay_sound_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_delay_sound_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_delay_sound_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_delay_sound_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_delay_sound_enable_war _null"

#define SETA_SCR_WEAPONJAMS_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_weaponjams_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_weaponjams_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_weaponjams_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_weaponjams_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_weaponjams_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_weaponjams_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_weaponjams_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_weaponjams_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_weaponjams_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_weaponjams_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_weaponjams_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_weaponjams_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_weaponjams_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_weaponjams_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_weaponjams_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_weaponjams_enable_war _null"

#define SETA_SCR_WEAPONJAMS_PROBABILITY \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_weaponjams_probability_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_weaponjams_probability_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_weaponjams_probability_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_weaponjams_probability_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_weaponjams_probability_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_weaponjams_probability_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_weaponjams_probability_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_weaponjams_probability_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_weaponjams_probability_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_weaponjams_probability_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_weaponjams_probability_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_weaponjams_probability_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_weaponjams_probability_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_weaponjams_probability_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_weaponjams_probability_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_weaponjams_probability_war _null"

#define SETA_SCR_WEAPONJAMS_GAP_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_weaponjams_gap_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_weaponjams_gap_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_weaponjams_gap_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_weaponjams_gap_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_weaponjams_gap_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_weaponjams_gap_time_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_weaponjams_gap_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_weaponjams_gap_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_weaponjams_gap_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_weaponjams_gap_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_weaponjams_gap_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_weaponjams_gap_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_weaponjams_gap_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_weaponjams_gap_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_weaponjams_gap_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_weaponjams_gap_time_war _null"

#define SETA_SCR_SNIPERZOOM_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_sniperzoom_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_sniperzoom_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_sniperzoom_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_sniperzoom_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_sniperzoom_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_sniperzoom_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_sniperzoom_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_sniperzoom_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_sniperzoom_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_sniperzoom_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_sniperzoom_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_sniperzoom_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_sniperzoom_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_sniperzoom_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_sniperzoom_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_sniperzoom_enable_war _null"

#define SETA_SCR_SNIPERZOOM_LOWER_LEVELS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_sniperzoom_lower_levels_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_sniperzoom_lower_levels_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_sniperzoom_lower_levels_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_sniperzoom_lower_levels_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_sniperzoom_lower_levels_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_sniperzoom_lower_levels_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_sniperzoom_lower_levels_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_sniperzoom_lower_levels_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_sniperzoom_lower_levels_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_sniperzoom_lower_levels_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_sniperzoom_lower_levels_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_sniperzoom_lower_levels_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_sniperzoom_lower_levels_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_sniperzoom_lower_levels_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_sniperzoom_lower_levels_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_sniperzoom_lower_levels_war _null"

#define SETA_SCR_SNIPERZOOM_UPPER_LEVELS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_sniperzoom_upper_levels_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_sniperzoom_upper_levels_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_sniperzoom_upper_levels_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_sniperzoom_upper_levels_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_sniperzoom_upper_levels_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_sniperzoom_upper_levels_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_sniperzoom_upper_levels_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_sniperzoom_upper_levels_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_sniperzoom_upper_levels_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_sniperzoom_upper_levels_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_sniperzoom_upper_levels_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_sniperzoom_upper_levels_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_sniperzoom_upper_levels_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_sniperzoom_upper_levels_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_sniperzoom_upper_levels_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_sniperzoom_upper_levels_war _null"

#define SETA_SCR_RANGEFINDER_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_rangefinder_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_rangefinder_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_rangefinder_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_rangefinder_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_rangefinder_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt dom "seta scr_rangefinder_enable_dom _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_rangefinder_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_rangefinder_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_rangefinder_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_rangefinder_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_rangefinder_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_rangefinder_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_rangefinder_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_rangefinder_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_rangefinder_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_rangefinder_enable_war _null"