#ifdef FILLMENUDVARS
#undef FILLMENUDVARS
#endif

#define FILLMENUDVARS     exec "exec menudvars/spectate/l/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/spectate/l/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/spectate/l/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/spectate/l/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/spectate/l/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/spectate/l/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/spectate/l/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/spectate/l/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/spectate/l/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/spectate/l/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/spectate/l/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt oitc "exec menudvars/spectate/l/oitc.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/spectate/l/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/spectate/l/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/spectate/l/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/spectate/l/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/spectate/l/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/spectate/l/war.cfg"



#define SETA_SCR_GAME_SPECTATETYPE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_game_spectatetype_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_game_spectatetype_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_game_spectatetype_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_game_spectatetype_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_game_spectatetype_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_game_spectatetype_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_game_spectatetype_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_game_spectatetype_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_game_spectatetype_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_game_spectatetype_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_game_spectatetype_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_game_spectatetype_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_game_spectatetype_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_game_spectatetype_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_game_spectatetype_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_game_spectatetype_war _null"

#define SETA_SCR_GAME_SPECTATETYPE_SPECTATORS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_game_spectatetype_spectators_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_game_spectatetype_spectators_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_game_spectatetype_spectators_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_game_spectatetype_spectators_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_game_spectatetype_spectators_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_game_spectatetype_spectators_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_game_spectatetype_spectators_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_game_spectatetype_spectators_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_game_spectatetype_spectators_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_game_spectatetype_spectators_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_game_spectatetype_spectators_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_game_spectatetype_spectators_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_game_spectatetype_spectators_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_game_spectatetype_spectators_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_game_spectatetype_spectators_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_game_spectatetype_spectators_war _null"

#define SETA_SCR_GAME_SPECTATORS_GUIDS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_game_spectators_guids_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_game_spectators_guids_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_game_spectators_guids_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_game_spectators_guids_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_game_spectators_guids_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_game_spectators_guids_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_game_spectators_guids_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_game_spectators_guids_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_game_spectators_guids_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_game_spectators_guids_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_game_spectators_guids_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_game_spectators_guids_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_game_spectators_guids_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_game_spectators_guids_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_game_spectators_guids_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_game_spectators_guids_war _null"

#define SETA_SCR_ALLOW_THIRDPERSON \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_allow_thirdperson_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_allow_thirdperson_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_allow_thirdperson_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_allow_thirdperson_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_allow_thirdperson_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_allow_thirdperson_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_allow_thirdperson_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_allow_thirdperson_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_allow_thirdperson_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_allow_thirdperson_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_allow_thirdperson_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_allow_thirdperson_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_allow_thirdperson_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_allow_thirdperson_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_allow_thirdperson_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_allow_thirdperson_war _null"

#define SETA_SCR_ALLOW_THIRDPERSON_GUIDS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_allow_thirdperson_guids_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_allow_thirdperson_guids_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_allow_thirdperson_guids_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_allow_thirdperson_guids_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_allow_thirdperson_guids_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_allow_thirdperson_guids_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_allow_thirdperson_guids_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_allow_thirdperson_guids_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_allow_thirdperson_guids_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_allow_thirdperson_guids_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_allow_thirdperson_guids_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_allow_thirdperson_guids_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_allow_thirdperson_guids_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_allow_thirdperson_guids_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_allow_thirdperson_guids_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_allow_thirdperson_guids_war _null"

#define SETA_SCR_LIVEBROADCAST_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_livebroadcast_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_livebroadcast_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_livebroadcast_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_livebroadcast_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_livebroadcast_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_livebroadcast_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_livebroadcast_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_livebroadcast_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_livebroadcast_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_livebroadcast_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_livebroadcast_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_livebroadcast_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_livebroadcast_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_livebroadcast_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_livebroadcast_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_livebroadcast_enable_war _null"

#define SETA_SCR_LIVEBROADCAST_GUIDS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_livebroadcast_guids_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_livebroadcast_guids_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_livebroadcast_guids_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_livebroadcast_guids_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_livebroadcast_guids_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_livebroadcast_guids_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_livebroadcast_guids_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_livebroadcast_guids_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_livebroadcast_guids_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_livebroadcast_guids_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_livebroadcast_guids_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_livebroadcast_guids_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_livebroadcast_guids_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_livebroadcast_guids_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_livebroadcast_guids_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_livebroadcast_guids_war _null"

#define SETA_SCR_IDLE_SWITCH_SPECTATOR \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_idle_switch_spectator_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_idle_switch_spectator_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_idle_switch_spectator_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_idle_switch_spectator_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_idle_switch_spectator_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_idle_switch_spectator_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_idle_switch_spectator_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_idle_switch_spectator_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_idle_switch_spectator_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_idle_switch_spectator_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_idle_switch_spectator_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_idle_switch_spectator_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_idle_switch_spectator_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_idle_switch_spectator_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_idle_switch_spectator_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_idle_switch_spectator_war _null"

#define SETA_SCR_IDLE_SPECTATOR_TIMEOUT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_idle_spectator_timeout_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_idle_spectator_timeout_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_idle_spectator_timeout_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_idle_spectator_timeout_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_idle_spectator_timeout_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_idle_spectator_timeout_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_idle_spectator_timeout_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_idle_spectator_timeout_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_idle_spectator_timeout_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_idle_spectator_timeout_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_idle_spectator_timeout_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_idle_spectator_timeout_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_idle_spectator_timeout_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_idle_spectator_timeout_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_idle_spectator_timeout_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_idle_spectator_timeout_war _null"

#define SETA_SCR_IDLE_SHOW_WARNING \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_idle_show_warning_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_idle_show_warning_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_idle_show_warning_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_idle_show_warning_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_idle_show_warning_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_idle_show_warning_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_idle_show_warning_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_idle_show_warning_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_idle_show_warning_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_idle_show_warning_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_idle_show_warning_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_idle_show_warning_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_idle_show_warning_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_idle_show_warning_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_idle_show_warning_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_idle_show_warning_war _null"

#define SETA_SCR_IDLE_PROTECTED_TAGS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_idle_protected_tags_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_idle_protected_tags_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_idle_protected_tags_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_idle_protected_tags_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_idle_protected_tags_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_idle_protected_tags_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_idle_protected_tags_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_idle_protected_tags_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_idle_protected_tags_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_idle_protected_tags_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_idle_protected_tags_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_idle_protected_tags_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_idle_protected_tags_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_idle_protected_tags_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_idle_protected_tags_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_idle_protected_tags_war _null"

#define SETA_SCR_IDLE_PROTECTED_GUIDS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_idle_protected_guids_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_idle_protected_guids_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_idle_protected_guids_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_idle_protected_guids_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_idle_protected_guids_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_idle_protected_guids_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_idle_protected_guids_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_idle_protected_guids_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_idle_protected_guids_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_idle_protected_guids_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_idle_protected_guids_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_idle_protected_guids_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_idle_protected_guids_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_idle_protected_guids_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_idle_protected_guids_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_idle_protected_guids_war _null"

