#ifdef FILLMENUDVARS
#undef FILLMENUDVARS
#endif

#define FILLMENUDVARS     exec "exec menudvars/perks/l/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/perks/l/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/perks/l/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/perks/l/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/perks/l/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/perks/l/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/perks/l/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/perks/l/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/perks/l/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/perks/l/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/perks/l/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt oitc "exec menudvars/perks/l/oitc.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/perks/l/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/perks/l/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/perks/l/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/perks/l/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/perks/l/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/perks/l/war.cfg"



#define SETA_PERK_ALLOW_C4_MP \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_c4_mp_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_c4_mp_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_c4_mp_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_c4_mp_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_c4_mp_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_c4_mp_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_c4_mp_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_c4_mp_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_c4_mp_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_c4_mp_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_c4_mp_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_c4_mp_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_c4_mp_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_c4_mp_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_c4_mp_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_c4_mp_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_SPECIALGRENADE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_specialgrenade_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_specialgrenade_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_specialgrenade_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_specialgrenade_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_specialgrenade_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_specialgrenade_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_specialgrenade_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_specialgrenade_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_specialgrenade_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_specialgrenade_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_specialgrenade_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_specialgrenade_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_specialgrenade_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_specialgrenade_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_specialgrenade_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_specialgrenade_war _null"

#define SETA_PERK_ALLOW_RPG_MP \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_rpg_mp_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_rpg_mp_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_rpg_mp_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_rpg_mp_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_rpg_mp_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_rpg_mp_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_rpg_mp_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_rpg_mp_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_rpg_mp_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_rpg_mp_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_rpg_mp_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_rpg_mp_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_rpg_mp_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_rpg_mp_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_rpg_mp_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_rpg_mp_war _null"

#define SETA_PERK_ALLOW_CLAYMORE_MP \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_claymore_mp_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_claymore_mp_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_claymore_mp_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_claymore_mp_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_claymore_mp_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_claymore_mp_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_claymore_mp_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_claymore_mp_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_claymore_mp_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_claymore_mp_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_claymore_mp_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_claymore_mp_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_claymore_mp_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_claymore_mp_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_claymore_mp_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_claymore_mp_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_FRAGGRENADE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_fraggrenade_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_fraggrenade_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_fraggrenade_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_fraggrenade_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_fraggrenade_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_fraggrenade_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_fraggrenade_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_fraggrenade_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_fraggrenade_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_fraggrenade_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_fraggrenade_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_fraggrenade_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_fraggrenade_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_fraggrenade_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_fraggrenade_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_fraggrenade_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_EXTRAAMMO \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_extraammo_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_extraammo_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_extraammo_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_extraammo_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_extraammo_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_extraammo_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_extraammo_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_extraammo_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_extraammo_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_extraammo_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_extraammo_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_extraammo_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_extraammo_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_extraammo_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_extraammo_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_extraammo_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_DETECTEXPLOSIVE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_detectexplosive_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_detectexplosive_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_detectexplosive_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_detectexplosive_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_detectexplosive_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_detectexplosive_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_detectexplosive_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_detectexplosive_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_detectexplosive_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_detectexplosive_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_detectexplosive_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_detectexplosive_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_detectexplosive_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_detectexplosive_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_detectexplosive_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_detectexplosive_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_BULLETDAMAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_bulletdamage_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_bulletdamage_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_bulletdamage_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_bulletdamage_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_bulletdamage_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_bulletdamage_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_bulletdamage_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_bulletdamage_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_bulletdamage_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_bulletdamage_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_bulletdamage_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_bulletdamage_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_bulletdamage_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_bulletdamage_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_bulletdamage_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_bulletdamage_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_ARMORVEST \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_armorvest_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_armorvest_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_armorvest_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_armorvest_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_armorvest_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_armorvest_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_armorvest_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_armorvest_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_armorvest_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_armorvest_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_armorvest_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_armorvest_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_armorvest_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_armorvest_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_armorvest_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_armorvest_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_FASTRELOAD \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_fastreload_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_fastreload_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_fastreload_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_fastreload_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_fastreload_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_fastreload_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_fastreload_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_fastreload_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_fastreload_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_fastreload_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_fastreload_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_fastreload_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_fastreload_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_fastreload_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_fastreload_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_fastreload_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_ROF \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_rof_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_rof_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_rof_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_rof_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_rof_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_rof_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_rof_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_rof_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_rof_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_rof_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_rof_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_rof_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_rof_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_rof_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_rof_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_rof_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_TWOPRIMARIES \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_twoprimaries_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_twoprimaries_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_twoprimaries_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_twoprimaries_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_twoprimaries_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_twoprimaries_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_twoprimaries_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_twoprimaries_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_twoprimaries_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_twoprimaries_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_twoprimaries_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_twoprimaries_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_twoprimaries_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_twoprimaries_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_twoprimaries_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_twoprimaries_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_GPSJAMMER \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_gpsjammer_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_gpsjammer_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_gpsjammer_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_gpsjammer_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_gpsjammer_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_gpsjammer_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_gpsjammer_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_gpsjammer_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_gpsjammer_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_gpsjammer_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_gpsjammer_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_gpsjammer_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_gpsjammer_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_gpsjammer_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_gpsjammer_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_gpsjammer_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_EXPLOSIVEDAMAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_explosivedamage_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_explosivedamage_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_explosivedamage_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_explosivedamage_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_explosivedamage_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_explosivedamage_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_explosivedamage_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_explosivedamage_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_explosivedamage_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_explosivedamage_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_explosivedamage_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_explosivedamage_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_explosivedamage_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_explosivedamage_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_explosivedamage_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_explosivedamage_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_LONGERSPRINT \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_longersprint_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_longersprint_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_longersprint_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_longersprint_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_longersprint_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_longersprint_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_longersprint_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_longersprint_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_longersprint_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_longersprint_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_longersprint_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_longersprint_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_longersprint_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_longersprint_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_longersprint_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_longersprint_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_BULLETACCURACY \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_bulletaccuracy_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_bulletaccuracy_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_bulletaccuracy_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_bulletaccuracy_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_bulletaccuracy_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_bulletaccuracy_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_bulletaccuracy_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_bulletaccuracy_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_bulletaccuracy_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_bulletaccuracy_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_bulletaccuracy_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_bulletaccuracy_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_bulletaccuracy_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_bulletaccuracy_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_bulletaccuracy_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_bulletaccuracy_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_PISTOLDEATH \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_pistoldeath_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_pistoldeath_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_pistoldeath_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_pistoldeath_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_pistoldeath_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_pistoldeath_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_pistoldeath_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_pistoldeath_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_pistoldeath_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_pistoldeath_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_pistoldeath_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_pistoldeath_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_pistoldeath_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_pistoldeath_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_pistoldeath_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_pistoldeath_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_GRENADEPULLDEATH \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_grenadepulldeath_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_grenadepulldeath_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_grenadepulldeath_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_grenadepulldeath_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_grenadepulldeath_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_grenadepulldeath_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_grenadepulldeath_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_grenadepulldeath_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_grenadepulldeath_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_grenadepulldeath_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_grenadepulldeath_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_grenadepulldeath_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_grenadepulldeath_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_grenadepulldeath_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_grenadepulldeath_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_grenadepulldeath_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_BULLETPENETRATION \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_bulletpenetration_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_bulletpenetration_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_bulletpenetration_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_bulletpenetration_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_bulletpenetration_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_bulletpenetration_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_bulletpenetration_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_bulletpenetration_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_bulletpenetration_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_bulletpenetration_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_bulletpenetration_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_bulletpenetration_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_bulletpenetration_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_bulletpenetration_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_bulletpenetration_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_bulletpenetration_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_HOLDBREATH \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_holdbreath_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_holdbreath_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_holdbreath_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_holdbreath_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_holdbreath_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_holdbreath_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_holdbreath_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_holdbreath_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_holdbreath_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_holdbreath_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_holdbreath_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_holdbreath_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_holdbreath_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_holdbreath_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_holdbreath_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_holdbreath_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_QUIETER \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_quieter_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_quieter_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_quieter_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_quieter_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_quieter_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_quieter_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_quieter_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_quieter_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_quieter_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_quieter_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_quieter_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_quieter_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_quieter_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_quieter_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_quieter_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_quieter_war _null"

#define SETA_PERK_ALLOW_SPECIALTY_PARABOLIC \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_allow_specialty_parabolic_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_allow_specialty_parabolic_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_allow_specialty_parabolic_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_allow_specialty_parabolic_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_allow_specialty_parabolic_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_allow_specialty_parabolic_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_allow_specialty_parabolic_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_allow_specialty_parabolic_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_allow_specialty_parabolic_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_allow_specialty_parabolic_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_allow_specialty_parabolic_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_allow_specialty_parabolic_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_allow_specialty_parabolic_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_allow_specialty_parabolic_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_allow_specialty_parabolic_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_allow_specialty_parabolic_war _null"

#define SETA_SCR_C4_AMMO_COUNT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_c4_ammo_count_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_c4_ammo_count_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_c4_ammo_count_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_c4_ammo_count_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_c4_ammo_count_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_c4_ammo_count_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_c4_ammo_count_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_c4_ammo_count_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_c4_ammo_count_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_c4_ammo_count_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_c4_ammo_count_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_c4_ammo_count_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_c4_ammo_count_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_c4_ammo_count_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_c4_ammo_count_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_c4_ammo_count_war _null"

#define SETA_SCR_CLAYMORE_AMMO_COUNT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_ammo_count_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_ammo_count_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_ammo_count_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_ammo_count_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_ammo_count_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_ammo_count_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_ammo_count_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_ammo_count_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_ammo_count_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_ammo_count_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_ammo_count_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_ammo_count_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_ammo_count_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_ammo_count_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_ammo_count_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_ammo_count_war _null"

#define SETA_SCR_RPG_AMMO_COUNT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_rpg_ammo_count_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_rpg_ammo_count_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_rpg_ammo_count_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_rpg_ammo_count_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_rpg_ammo_count_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_rpg_ammo_count_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_rpg_ammo_count_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_rpg_ammo_count_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_rpg_ammo_count_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_rpg_ammo_count_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_rpg_ammo_count_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_rpg_ammo_count_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_rpg_ammo_count_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_rpg_ammo_count_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_rpg_ammo_count_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_rpg_ammo_count_war _null"

#define SETA_SPECIALTY_FRAGGRENADE_AMMO_COUNT \
  execOnDvarStringValue menu_cfg_gt ass "seta specialty_fraggrenade_ammo_count_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta specialty_fraggrenade_ammo_count_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta specialty_fraggrenade_ammo_count_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta specialty_fraggrenade_ammo_count_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta specialty_fraggrenade_ammo_count_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta specialty_fraggrenade_ammo_count_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta specialty_fraggrenade_ammo_count_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta specialty_fraggrenade_ammo_count_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta specialty_fraggrenade_ammo_count_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta specialty_fraggrenade_ammo_count_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta specialty_fraggrenade_ammo_count_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta specialty_fraggrenade_ammo_count_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta specialty_fraggrenade_ammo_count_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta specialty_fraggrenade_ammo_count_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta specialty_fraggrenade_ammo_count_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta specialty_fraggrenade_ammo_count_war _null"

#define SETA_SPECIALTY_SPECIALGRENADE_AMMO_COUNT \
  execOnDvarStringValue menu_cfg_gt ass "seta specialty_specialgrenade_ammo_count_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta specialty_specialgrenade_ammo_count_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta specialty_specialgrenade_ammo_count_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta specialty_specialgrenade_ammo_count_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta specialty_specialgrenade_ammo_count_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta specialty_specialgrenade_ammo_count_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta specialty_specialgrenade_ammo_count_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta specialty_specialgrenade_ammo_count_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta specialty_specialgrenade_ammo_count_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta specialty_specialgrenade_ammo_count_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta specialty_specialgrenade_ammo_count_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta specialty_specialgrenade_ammo_count_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta specialty_specialgrenade_ammo_count_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta specialty_specialgrenade_ammo_count_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta specialty_specialgrenade_ammo_count_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta specialty_specialgrenade_ammo_count_war _null"

#define SETA_PERK_ARMORVEST \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_armorvest_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_armorvest_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_armorvest_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_armorvest_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_armorvest_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_armorvest_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_armorvest_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_armorvest_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_armorvest_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_armorvest_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_armorvest_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_armorvest_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_armorvest_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_armorvest_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_armorvest_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_armorvest_war _null"

#define SETA_PERK_BULLETDAMAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_bulletdamage_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_bulletdamage_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_bulletdamage_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_bulletdamage_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_bulletdamage_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_bulletdamage_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_bulletdamage_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_bulletdamage_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_bulletdamage_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_bulletdamage_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_bulletdamage_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_bulletdamage_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_bulletdamage_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_bulletdamage_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_bulletdamage_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_bulletdamage_war _null"

#define SETA_PERK_EXPLOSIVEDAMAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta perk_explosivedamage_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta perk_explosivedamage_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta perk_explosivedamage_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta perk_explosivedamage_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta perk_explosivedamage_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta perk_explosivedamage_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta perk_explosivedamage_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta perk_explosivedamage_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta perk_explosivedamage_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta perk_explosivedamage_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta perk_explosivedamage_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta perk_explosivedamage_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta perk_explosivedamage_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta perk_explosivedamage_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta perk_explosivedamage_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta perk_explosivedamage_war _null"

#define SETA_SCR_CLAYMORE_FRIENDLY_FIRE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_friendly_fire_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_friendly_fire_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_friendly_fire_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_friendly_fire_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_friendly_fire_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_friendly_fire_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_friendly_fire_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_friendly_fire_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_friendly_fire_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_friendly_fire_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_friendly_fire_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_friendly_fire_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_friendly_fire_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_friendly_fire_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_friendly_fire_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_friendly_fire_war _null"

#define SETA_SPECIALTY_GRENADEPULLDEATH_CHECK_FRAGS \
  execOnDvarStringValue menu_cfg_gt ass "seta specialty_grenadepulldeath_check_frags_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta specialty_grenadepulldeath_check_frags_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta specialty_grenadepulldeath_check_frags_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta specialty_grenadepulldeath_check_frags_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta specialty_grenadepulldeath_check_frags_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta specialty_grenadepulldeath_check_frags_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta specialty_grenadepulldeath_check_frags_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta specialty_grenadepulldeath_check_frags_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta specialty_grenadepulldeath_check_frags_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta specialty_grenadepulldeath_check_frags_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta specialty_grenadepulldeath_check_frags_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta specialty_grenadepulldeath_check_frags_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta specialty_grenadepulldeath_check_frags_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta specialty_grenadepulldeath_check_frags_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta specialty_grenadepulldeath_check_frags_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta specialty_grenadepulldeath_check_frags_war _null"

#define SETA_SPECIALTY_PISTOLDEATH_CHECK_PISTOL \
  execOnDvarStringValue menu_cfg_gt ass "seta specialty_pistoldeath_check_pistol_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta specialty_pistoldeath_check_pistol_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta specialty_pistoldeath_check_pistol_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta specialty_pistoldeath_check_pistol_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta specialty_pistoldeath_check_pistol_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta specialty_pistoldeath_check_pistol_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta specialty_pistoldeath_check_pistol_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta specialty_pistoldeath_check_pistol_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta specialty_pistoldeath_check_pistol_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta specialty_pistoldeath_check_pistol_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta specialty_pistoldeath_check_pistol_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta specialty_pistoldeath_check_pistol_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta specialty_pistoldeath_check_pistol_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta specialty_pistoldeath_check_pistol_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta specialty_pistoldeath_check_pistol_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta specialty_pistoldeath_check_pistol_war _null"

#define SETA_SCR_CLAYMORE_CHECK_PLANT_DISTANCE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_check_plant_distance_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_check_plant_distance_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_check_plant_distance_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_check_plant_distance_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_check_plant_distance_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_check_plant_distance_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_check_plant_distance_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_check_plant_distance_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_check_plant_distance_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_check_plant_distance_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_check_plant_distance_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_check_plant_distance_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_check_plant_distance_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_check_plant_distance_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_check_plant_distance_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_check_plant_distance_war _null"

#define SETA_SCR_CLAYMORE_ADD_KILL_ONLY_IF_DIRECTED \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_add_kill_only_if_directed_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_add_kill_only_if_directed_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_add_kill_only_if_directed_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_add_kill_only_if_directed_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_add_kill_only_if_directed_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_add_kill_only_if_directed_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_add_kill_only_if_directed_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_add_kill_only_if_directed_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_add_kill_only_if_directed_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_add_kill_only_if_directed_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_add_kill_only_if_directed_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_add_kill_only_if_directed_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_add_kill_only_if_directed_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_add_kill_only_if_directed_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_add_kill_only_if_directed_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_add_kill_only_if_directed_war _null"

#define SETA_SCR_CLAYMORE_ARM_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_arm_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_arm_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_arm_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_arm_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_arm_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_arm_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_arm_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_arm_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_arm_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_arm_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_arm_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_arm_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_arm_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_arm_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_arm_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_arm_time_war _null"

#define SETA_SCR_EXPLOSIVES_ALLOW_DISARM \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_explosives_allow_disarm_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_explosives_allow_disarm_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_explosives_allow_disarm_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_explosives_allow_disarm_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_explosives_allow_disarm_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_explosives_allow_disarm_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_explosives_allow_disarm_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_explosives_allow_disarm_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_explosives_allow_disarm_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_explosives_allow_disarm_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_explosives_allow_disarm_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_explosives_allow_disarm_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_explosives_allow_disarm_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_explosives_allow_disarm_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_explosives_allow_disarm_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_explosives_allow_disarm_war _null"

#define SETA_SCR_EXPLOSIVES_DISARM_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_explosives_disarm_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_explosives_disarm_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_explosives_disarm_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_explosives_disarm_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_explosives_disarm_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_explosives_disarm_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_explosives_disarm_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_explosives_disarm_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_explosives_disarm_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_explosives_disarm_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_explosives_disarm_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_explosives_disarm_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_explosives_disarm_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_explosives_disarm_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_explosives_disarm_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_explosives_disarm_time_war _null"

#define SETA_SCR_CLAYMORE_SHOW_HEADICON \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_show_headicon_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_show_headicon_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_show_headicon_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_show_headicon_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_show_headicon_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_show_headicon_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_show_headicon_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_show_headicon_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_show_headicon_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_show_headicon_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_show_headicon_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_show_headicon_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_show_headicon_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_show_headicon_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_show_headicon_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_show_headicon_war _null"

#define SETA_SCR_CLAYMORE_SHOW_LASER_BEAMS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_claymore_show_laser_beams_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_claymore_show_laser_beams_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_claymore_show_laser_beams_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_claymore_show_laser_beams_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_claymore_show_laser_beams_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_claymore_show_laser_beams_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_claymore_show_laser_beams_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_claymore_show_laser_beams_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_claymore_show_laser_beams_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_claymore_show_laser_beams_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_claymore_show_laser_beams_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_claymore_show_laser_beams_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_claymore_show_laser_beams_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_claymore_show_laser_beams_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_claymore_show_laser_beams_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_claymore_show_laser_beams_war _null"

#define SETA_SCR_SHOW_C4_BLINK_EFFECT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_show_c4_blink_effect_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_show_c4_blink_effect_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_show_c4_blink_effect_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_show_c4_blink_effect_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_show_c4_blink_effect_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_show_c4_blink_effect_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_show_c4_blink_effect_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_show_c4_blink_effect_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_show_c4_blink_effect_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_show_c4_blink_effect_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_show_c4_blink_effect_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_show_c4_blink_effect_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_show_c4_blink_effect_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_show_c4_blink_effect_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_show_c4_blink_effect_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_show_c4_blink_effect_war _null"