#ifdef FILLMENUDVARS
  #undef FILLMENUDVARS
#endif

#define FILLMENUDVARS     exec "exec menudvars/weapons/l/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/weapons/l/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/weapons/l/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/weapons/l/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/weapons/l/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/weapons/l/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/weapons/l/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/weapons/l/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/weapons/l/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/weapons/l/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/weapons/l/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt oitc "exec menudvars/weapons/l/oitc.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/weapons/l/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/weapons/l/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/weapons/l/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/weapons/l/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/weapons/l/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/weapons/l/war.cfg"

    
    
#define SETA_WEAP_ALLOW_ASSAULT_M16 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_m16_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_m16_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_m16_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_m16_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_m16_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_m16_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_m16_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_m16_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_m16_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_m16_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_m16_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_m16_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_m16_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_m16_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_m16_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_m16_war _null"
  
#define SETA_WEAP_ALLOW_ASSAULT_AK47 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_ak47_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_ak47_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_ak47_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_ak47_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_ak47_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_ak47_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_ak47_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_ak47_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_ak47_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_ak47_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_ak47_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_ak47_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_ak47_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_ak47_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_ak47_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_ak47_war _null"
  
#define SETA_WEAP_ALLOW_ASSAULT_M4 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_m4_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_m4_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_m4_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_m4_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_m4_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_m4_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_m4_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_m4_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_m4_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_m4_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_m4_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_m4_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_m4_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_m4_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_m4_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_m4_war _null"
  
#define SETA_WEAP_ALLOW_ASSAULT_G3 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_g3_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_g3_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_g3_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_g3_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_g3_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_g3_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_g3_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_g3_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_g3_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_g3_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_g3_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_g3_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_g3_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_g3_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_g3_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_g3_war _null"
  
#define SETA_WEAP_ALLOW_ASSAULT_G36C \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_g36c_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_g36c_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_g36c_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_g36c_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_g36c_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_g36c_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_g36c_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_g36c_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_g36c_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_g36c_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_g36c_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_g36c_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_g36c_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_g36c_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_g36c_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_g36c_war _null"
  
#define SETA_WEAP_ALLOW_ASSAULT_M14 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_m14_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_m14_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_m14_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_m14_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_m14_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_m14_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_m14_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_m14_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_m14_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_m14_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_m14_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_m14_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_m14_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_m14_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_m14_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_m14_war _null"
  
#define SETA_WEAP_ALLOW_ASSAULT_MP44 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_assault_mp44_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_assault_mp44_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_assault_mp44_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_assault_mp44_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_assault_mp44_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_assault_mp44_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_assault_mp44_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_assault_mp44_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_assault_mp44_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_assault_mp44_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_assault_mp44_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_assault_mp44_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_assault_mp44_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_assault_mp44_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_assault_mp44_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_assault_mp44_war _null"
  
#define SETA_WEAP_ALLOW_SPECOPS_MP5 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_specops_mp5_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_specops_mp5_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_specops_mp5_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_specops_mp5_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_specops_mp5_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_specops_mp5_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_specops_mp5_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_specops_mp5_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_specops_mp5_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_specops_mp5_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_specops_mp5_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_specops_mp5_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_specops_mp5_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_specops_mp5_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_specops_mp5_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_specops_mp5_war _null"
  
#define SETA_WEAP_ALLOW_SPECOPS_SKORPION \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_specops_skorpion_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_specops_skorpion_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_specops_skorpion_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_specops_skorpion_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_specops_skorpion_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_specops_skorpion_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_specops_skorpion_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_specops_skorpion_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_specops_skorpion_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_specops_skorpion_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_specops_skorpion_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_specops_skorpion_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_specops_skorpion_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_specops_skorpion_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_specops_skorpion_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_specops_skorpion_war _null"
  
#define SETA_WEAP_ALLOW_SPECOPS_UZI \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_specops_uzi_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_specops_uzi_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_specops_uzi_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_specops_uzi_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_specops_uzi_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_specops_uzi_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_specops_uzi_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_specops_uzi_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_specops_uzi_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_specops_uzi_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_specops_uzi_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_specops_uzi_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_specops_uzi_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_specops_uzi_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_specops_uzi_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_specops_uzi_war _null"
  
#define SETA_WEAP_ALLOW_SPECOPS_AK74U \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_specops_ak74u_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_specops_ak74u_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_specops_ak74u_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_specops_ak74u_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_specops_ak74u_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_specops_ak74u_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_specops_ak74u_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_specops_ak74u_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_specops_ak74u_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_specops_ak74u_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_specops_ak74u_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_specops_ak74u_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_specops_ak74u_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_specops_ak74u_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_specops_ak74u_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_specops_ak74u_war _null"
  
#define SETA_WEAP_ALLOW_SPECOPS_P90 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_specops_p90_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_specops_p90_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_specops_p90_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_specops_p90_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_specops_p90_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_specops_p90_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_specops_p90_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_specops_p90_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_specops_p90_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_specops_p90_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_specops_p90_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_specops_p90_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_specops_p90_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_specops_p90_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_specops_p90_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_specops_p90_war _null"
  
#define SETA_WEAP_ALLOW_HEAVYGUNNER_SAW \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_heavygunner_saw_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_heavygunner_saw_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_heavygunner_saw_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_heavygunner_saw_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_heavygunner_saw_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_heavygunner_saw_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_heavygunner_saw_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_heavygunner_saw_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_heavygunner_saw_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_heavygunner_saw_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_heavygunner_saw_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_heavygunner_saw_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_heavygunner_saw_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_heavygunner_saw_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_heavygunner_saw_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_heavygunner_saw_war _null"
  
#define SETA_WEAP_ALLOW_HEAVYGUNNER_RPD \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_heavygunner_rpd_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_heavygunner_rpd_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_heavygunner_rpd_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_heavygunner_rpd_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_heavygunner_rpd_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_heavygunner_rpd_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_heavygunner_rpd_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_heavygunner_rpd_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_heavygunner_rpd_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_heavygunner_rpd_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_heavygunner_rpd_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_heavygunner_rpd_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_heavygunner_rpd_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_heavygunner_rpd_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_heavygunner_rpd_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_heavygunner_rpd_war _null"
  
#define SETA_WEAP_ALLOW_HEAVYGUNNER_M60E4 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_heavygunner_m60e4_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_heavygunner_m60e4_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_heavygunner_m60e4_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_heavygunner_m60e4_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_heavygunner_m60e4_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_heavygunner_m60e4_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_heavygunner_m60e4_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_heavygunner_m60e4_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_heavygunner_m60e4_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_heavygunner_m60e4_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_heavygunner_m60e4_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_heavygunner_m60e4_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_heavygunner_m60e4_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_heavygunner_m60e4_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_heavygunner_m60e4_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_heavygunner_m60e4_war _null"
  
#define SETA_WEAP_ALLOW_DEMOLITIONS_WINCHESTER1200 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_demolitions_winchester1200_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_demolitions_winchester1200_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_demolitions_winchester1200_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_demolitions_winchester1200_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_demolitions_winchester1200_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_demolitions_winchester1200_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_demolitions_winchester1200_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_demolitions_winchester1200_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_demolitions_winchester1200_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_demolitions_winchester1200_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_demolitions_winchester1200_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_demolitions_winchester1200_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_demolitions_winchester1200_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_demolitions_winchester1200_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_demolitions_winchester1200_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_demolitions_winchester1200_war _null"
  
#define SETA_WEAP_ALLOW_DEMOLITIONS_M1014 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_demolitions_m1014_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_demolitions_m1014_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_demolitions_m1014_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_demolitions_m1014_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_demolitions_m1014_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_demolitions_m1014_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_demolitions_m1014_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_demolitions_m1014_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_demolitions_m1014_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_demolitions_m1014_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_demolitions_m1014_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_demolitions_m1014_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_demolitions_m1014_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_demolitions_m1014_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_demolitions_m1014_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_demolitions_m1014_war _null"
  
#define SETA_WEAP_ALLOW_SNIPER_M40A3 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_sniper_m40a3_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_sniper_m40a3_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_sniper_m40a3_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_sniper_m40a3_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_sniper_m40a3_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_sniper_m40a3_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_sniper_m40a3_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_sniper_m40a3_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_sniper_m40a3_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_sniper_m40a3_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_sniper_m40a3_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_sniper_m40a3_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_sniper_m40a3_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_sniper_m40a3_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_sniper_m40a3_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_sniper_m40a3_war _null"
  
#define SETA_WEAP_ALLOW_SNIPER_M21 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_sniper_m21_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_sniper_m21_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_sniper_m21_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_sniper_m21_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_sniper_m21_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_sniper_m21_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_sniper_m21_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_sniper_m21_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_sniper_m21_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_sniper_m21_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_sniper_m21_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_sniper_m21_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_sniper_m21_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_sniper_m21_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_sniper_m21_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_sniper_m21_war _null"
  
#define SETA_WEAP_ALLOW_SNIPER_DRAGUNOV \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_sniper_dragunov_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_sniper_dragunov_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_sniper_dragunov_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_sniper_dragunov_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_sniper_dragunov_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_sniper_dragunov_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_sniper_dragunov_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_sniper_dragunov_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_sniper_dragunov_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_sniper_dragunov_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_sniper_dragunov_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_sniper_dragunov_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_sniper_dragunov_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_sniper_dragunov_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_sniper_dragunov_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_sniper_dragunov_war _null"
  
#define SETA_WEAP_ALLOW_SNIPER_REMINGTON700 \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_sniper_remington700_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_sniper_remington700_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_sniper_remington700_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_sniper_remington700_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_sniper_remington700_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_sniper_remington700_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_sniper_remington700_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_sniper_remington700_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_sniper_remington700_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_sniper_remington700_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_sniper_remington700_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_sniper_remington700_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_sniper_remington700_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_sniper_remington700_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_sniper_remington700_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_sniper_remington700_war _null"
  
#define SETA_WEAP_ALLOW_SNIPER_BARRETT \
  execOnDvarStringValue menu_cfg_gt ass "seta weap_allow_sniper_barrett_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta weap_allow_sniper_barrett_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta weap_allow_sniper_barrett_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta weap_allow_sniper_barrett_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta weap_allow_sniper_barrett_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta weap_allow_sniper_barrett_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta weap_allow_sniper_barrett_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta weap_allow_sniper_barrett_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta weap_allow_sniper_barrett_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta weap_allow_sniper_barrett_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta weap_allow_sniper_barrett_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta weap_allow_sniper_barrett_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta weap_allow_sniper_barrett_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta weap_allow_sniper_barrett_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta weap_allow_sniper_barrett_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta weap_allow_sniper_barrett_war _null"