#ifdef FILLMENUDVARS
  #undef FILLMENUDVARS
#endif

#define FILLMENUDVARS     exec "exec menudvars/fairness/l/_def.cfg"\
    execOnDvarStringValue menu_cfg_gt ass "exec menudvars/fairness/l/ass.cfg"\
    execOnDvarStringValue menu_cfg_gt bel "exec menudvars/fairness/l/bel.cfg"\
    execOnDvarStringValue menu_cfg_gt ch "exec menudvars/fairness/l/ch.cfg"\
    execOnDvarStringValue menu_cfg_gt ctf "exec menudvars/fairness/l/ctf.cfg"\
    execOnDvarStringValue menu_cfg_gt dm "exec menudvars/fairness/l/dm.cfg"\
    execOnDvarStringValue menu_cfg_gt dom "exec menudvars/fairness/l/dom.cfg"\
    execOnDvarStringValue menu_cfg_gt ftag "exec menudvars/fairness/l/ftag.cfg"\
    execOnDvarStringValue menu_cfg_gt gg "exec menudvars/fairness/l/gg.cfg"\
    execOnDvarStringValue menu_cfg_gt gr "exec menudvars/fairness/l/gr.cfg"\
    execOnDvarStringValue menu_cfg_gt koth "exec menudvars/fairness/l/koth.cfg"\
    execOnDvarStringValue menu_cfg_gt oitc "exec menudvars/fairness/l/oitc.cfg"\
    execOnDvarStringValue menu_cfg_gt re "exec menudvars/fairness/l/re.cfg"\
    execOnDvarStringValue menu_cfg_gt sab "exec menudvars/fairness/l/sab.cfg"\
    execOnDvarStringValue menu_cfg_gt sd "exec menudvars/fairness/l/sd.cfg"\
    execOnDvarStringValue menu_cfg_gt ss "exec menudvars/fairness/l/ss.cfg"\
    execOnDvarStringValue menu_cfg_gt tgr "exec menudvars/fairness/l/tgr.cfg"\
    execOnDvarStringValue menu_cfg_gt war "exec menudvars/fairness/l/war.cfg"

    
    
#define SETA_SCR_FORCE_AUTOASSIGN \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_force_autoassign_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_force_autoassign_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_force_autoassign_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_force_autoassign_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_force_autoassign_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_force_autoassign_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_force_autoassign_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_force_autoassign_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_force_autoassign_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_force_autoassign_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_force_autoassign_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_force_autoassign_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_force_autoassign_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_force_autoassign_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_force_autoassign_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_force_autoassign_war _null"
  
#define SETA_SCR_FORCE_AUTOASSIGN_CLAN_TAGS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_force_autoassign_clan_tags_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_force_autoassign_clan_tags_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_force_autoassign_clan_tags_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_force_autoassign_clan_tags_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_force_autoassign_clan_tags_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_force_autoassign_clan_tags_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_force_autoassign_clan_tags_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_force_autoassign_clan_tags_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_force_autoassign_clan_tags_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_force_autoassign_clan_tags_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_force_autoassign_clan_tags_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_force_autoassign_clan_tags_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_force_autoassign_clan_tags_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_force_autoassign_clan_tags_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_force_autoassign_clan_tags_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_force_autoassign_clan_tags_war _null"
  
#define SETA_SCR_SWITCH_TEAMS_AT_HALFTIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_switch_teams_at_halftime_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_switch_teams_at_halftime_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_switch_teams_at_halftime_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_switch_teams_at_halftime_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_switch_teams_at_halftime_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_switch_teams_at_halftime_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_switch_teams_at_halftime_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_switch_teams_at_halftime_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_switch_teams_at_halftime_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_switch_teams_at_halftime_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_switch_teams_at_halftime_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_switch_teams_at_halftime_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_switch_teams_at_halftime_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_switch_teams_at_halftime_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_switch_teams_at_halftime_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_switch_teams_at_halftime_war _null"
  
#define SETA_SCR_TEAMBALANCE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_teambalance_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_teambalance_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_teambalance_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_teambalance_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_teambalance_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_teambalance_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_teambalance_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_teambalance_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_teambalance_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_teambalance_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_teambalance_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_teambalance_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_teambalance_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_teambalance_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_teambalance_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_teambalance_war _null"
  
#define SETA_SCR_TEAMBALANCE_SHOW_MESSAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_teambalance_show_message_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_teambalance_show_message_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_teambalance_show_message_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_teambalance_show_message_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_teambalance_show_message_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_teambalance_show_message_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_teambalance_show_message_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_teambalance_show_message_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_teambalance_show_message_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_teambalance_show_message_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_teambalance_show_message_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_teambalance_show_message_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_teambalance_show_message_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_teambalance_show_message_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_teambalance_show_message_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_teambalance_show_message_war _null"
  
#define SETA_SCR_TEAMBALANCE_CHECK_INTERVAL \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_teambalance_check_interval_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_teambalance_check_interval_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_teambalance_check_interval_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_teambalance_check_interval_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_teambalance_check_interval_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_teambalance_check_interval_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_teambalance_check_interval_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_teambalance_check_interval_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_teambalance_check_interval_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_teambalance_check_interval_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_teambalance_check_interval_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_teambalance_check_interval_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_teambalance_check_interval_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_teambalance_check_interval_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_teambalance_check_interval_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_teambalance_check_interval_war _null"
  
#define SETA_SCR_TEAMBALANCE_DELAY \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_teambalance_delay_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_teambalance_delay_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_teambalance_delay_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_teambalance_delay_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_teambalance_delay_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_teambalance_delay_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_teambalance_delay_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_teambalance_delay_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_teambalance_delay_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_teambalance_delay_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_teambalance_delay_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_teambalance_delay_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_teambalance_delay_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_teambalance_delay_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_teambalance_delay_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_teambalance_delay_war _null"
  
#define SETA_SCR_TEAMBALANCE_PROTECTED_CLAN_TAGS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_teambalance_protected_clan_tags_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_teambalance_protected_clan_tags_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_teambalance_protected_clan_tags_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_teambalance_protected_clan_tags_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_teambalance_protected_clan_tags_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_teambalance_protected_clan_tags_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_teambalance_protected_clan_tags_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_teambalance_protected_clan_tags_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_teambalance_protected_clan_tags_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_teambalance_protected_clan_tags_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_teambalance_protected_clan_tags_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_teambalance_protected_clan_tags_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_teambalance_protected_clan_tags_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_teambalance_protected_clan_tags_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_teambalance_protected_clan_tags_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_teambalance_protected_clan_tags_war _null"
  
#define SETA_SCR_TEAM_FFTYPE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_team_fftype_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_team_fftype_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_team_fftype_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_team_fftype_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_team_fftype_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_team_fftype_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_team_fftype_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_team_fftype_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_team_fftype_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_team_fftype_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_team_fftype_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_team_fftype_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_team_fftype_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_team_fftype_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_team_fftype_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_team_fftype_war _null"
  
#define SETA_SCR_TEAM_TEAMKILLPOINTLOSS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_team_teamkillpointloss_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_team_teamkillpointloss_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_team_teamkillpointloss_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_team_teamkillpointloss_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_team_teamkillpointloss_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_team_teamkillpointloss_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_team_teamkillpointloss_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_team_teamkillpointloss_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_team_teamkillpointloss_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_team_teamkillpointloss_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_team_teamkillpointloss_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_team_teamkillpointloss_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_team_teamkillpointloss_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_team_teamkillpointloss_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_team_teamkillpointloss_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_team_teamkillpointloss_war _null"
  
#define SETA_SCR_TEAM_TEAMKILLSPAWNDELAY \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_team_teamkillspawndelay_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_team_teamkillspawndelay_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_team_teamkillspawndelay_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_team_teamkillspawndelay_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_team_teamkillspawndelay_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_team_teamkillspawndelay_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_team_teamkillspawndelay_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_team_teamkillspawndelay_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_team_teamkillspawndelay_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_team_teamkillspawndelay_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_team_teamkillspawndelay_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_team_teamkillspawndelay_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_team_teamkillspawndelay_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_team_teamkillspawndelay_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_team_teamkillspawndelay_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_team_teamkillspawndelay_war _null"
  
#define SETA_SCR_GAME_DEATHPOINTLOSS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_game_deathpointloss_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_game_deathpointloss_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_game_deathpointloss_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_game_deathpointloss_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_game_deathpointloss_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_game_deathpointloss_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_game_deathpointloss_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_game_deathpointloss_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_game_deathpointloss_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_game_deathpointloss_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_game_deathpointloss_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_game_deathpointloss_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_game_deathpointloss_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_game_deathpointloss_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_game_deathpointloss_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_game_deathpointloss_war _null"
  
#define SETA_SCR_GAME_SUICIDEPOINTLOSS \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_game_suicidepointloss_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_game_suicidepointloss_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_game_suicidepointloss_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_game_suicidepointloss_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_game_suicidepointloss_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_game_suicidepointloss_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_game_suicidepointloss_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_game_suicidepointloss_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_game_suicidepointloss_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_game_suicidepointloss_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_game_suicidepointloss_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_game_suicidepointloss_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_game_suicidepointloss_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_game_suicidepointloss_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_game_suicidepointloss_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_game_suicidepointloss_war _null"
  
#define SETA_SCR_PLAYER_SUICIDESPAWNDELAY \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_player_suicidespawndelay_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_player_suicidespawndelay_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_player_suicidespawndelay_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_player_suicidespawndelay_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_player_suicidespawndelay_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_player_suicidespawndelay_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_player_suicidespawndelay_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_player_suicidespawndelay_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_player_suicidespawndelay_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_player_suicidespawndelay_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_player_suicidespawndelay_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_player_suicidespawndelay_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_player_suicidespawndelay_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_player_suicidespawndelay_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_player_suicidespawndelay_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_player_suicidespawndelay_war _null"
  
#define SETA_SCR_TK_LIMIT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_tk_limit_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_tk_limit_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_tk_limit_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_tk_limit_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_tk_limit_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_tk_limit_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_tk_limit_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_tk_limit_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_tk_limit_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_tk_limit_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_tk_limit_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_tk_limit_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_tk_limit_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_tk_limit_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_tk_limit_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_tk_limit_war _null"
  
#define SETA_SCR_TK_EXPLOSIVE_COUNTASONE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_tk_explosive_countasone_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_tk_explosive_countasone_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_tk_explosive_countasone_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_tk_explosive_countasone_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_tk_explosive_countasone_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_tk_explosive_countasone_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_tk_explosive_countasone_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_tk_explosive_countasone_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_tk_explosive_countasone_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_tk_explosive_countasone_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_tk_explosive_countasone_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_tk_explosive_countasone_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_tk_explosive_countasone_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_tk_explosive_countasone_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_tk_explosive_countasone_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_tk_explosive_countasone_war _null"
  
#define SETA_SCR_TK_PUNISHMENT \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_tk_punishment_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_tk_punishment_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_tk_punishment_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_tk_punishment_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_tk_punishment_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_tk_punishment_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_tk_punishment_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_tk_punishment_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_tk_punishment_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_tk_punishment_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_tk_punishment_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_tk_punishment_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_tk_punishment_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_tk_punishment_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_tk_punishment_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_tk_punishment_war _null"
  
#define SETA_SCR_TK_PUNISHMENT_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_tk_punishment_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_tk_punishment_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_tk_punishment_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_tk_punishment_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_tk_punishment_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_tk_punishment_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_tk_punishment_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_tk_punishment_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_tk_punishment_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_tk_punishment_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_tk_punishment_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_tk_punishment_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_tk_punishment_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_tk_punishment_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_tk_punishment_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_tk_punishment_time_war _null"
  
#define SETA_SCR_SPAWN_PROTECTION_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_spawn_protection_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_spawn_protection_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_spawn_protection_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_spawn_protection_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_spawn_protection_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_spawn_protection_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_spawn_protection_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_spawn_protection_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_spawn_protection_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_spawn_protection_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_spawn_protection_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_spawn_protection_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_spawn_protection_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_spawn_protection_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_spawn_protection_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_spawn_protection_enable_war _null"
  
#define SETA_SCR_SPAWN_PROTECTION_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_spawn_protection_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_spawn_protection_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_spawn_protection_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_spawn_protection_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_spawn_protection_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_spawn_protection_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_spawn_protection_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_spawn_protection_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_spawn_protection_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_spawn_protection_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_spawn_protection_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_spawn_protection_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_spawn_protection_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_spawn_protection_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_spawn_protection_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_spawn_protection_time_war _null"
  
#define SETA_SCR_SPAWN_PROTECTION_INVISIBLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_spawn_protection_invisible_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_spawn_protection_invisible_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_spawn_protection_invisible_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_spawn_protection_invisible_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_spawn_protection_invisible_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_spawn_protection_invisible_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_spawn_protection_invisible_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_spawn_protection_invisible_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_spawn_protection_invisible_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_spawn_protection_invisible_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_spawn_protection_invisible_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_spawn_protection_invisible_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_spawn_protection_invisible_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_spawn_protection_invisible_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_spawn_protection_invisible_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_spawn_protection_invisible_war _null"
  
#define SETA_SCR_SPAWN_PROTECTION_HITICON \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_spawn_protection_hiticon_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_spawn_protection_hiticon_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_spawn_protection_hiticon_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_spawn_protection_hiticon_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_spawn_protection_hiticon_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_spawn_protection_hiticon_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_spawn_protection_hiticon_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_spawn_protection_hiticon_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_spawn_protection_hiticon_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_spawn_protection_hiticon_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_spawn_protection_hiticon_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_spawn_protection_hiticon_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_spawn_protection_hiticon_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_spawn_protection_hiticon_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_spawn_protection_hiticon_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_spawn_protection_hiticon_war _null"
  
#define SETA_SCR_SPAWN_PROTECTION_MAXDISTANCE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_spawn_protection_maxdistance_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_spawn_protection_maxdistance_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_spawn_protection_maxdistance_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_spawn_protection_maxdistance_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_spawn_protection_maxdistance_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_spawn_protection_maxdistance_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_spawn_protection_maxdistance_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_spawn_protection_maxdistance_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_spawn_protection_maxdistance_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_spawn_protection_maxdistance_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_spawn_protection_maxdistance_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_spawn_protection_maxdistance_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_spawn_protection_maxdistance_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_spawn_protection_maxdistance_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_spawn_protection_maxdistance_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_spawn_protection_maxdistance_war _null"
  
#define SETA_SCR_SPAWN_PROTECTION_PUNISHMENT_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_spawn_protection_punishment_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_spawn_protection_punishment_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_spawn_protection_punishment_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_spawn_protection_punishment_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_spawn_protection_punishment_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_spawn_protection_punishment_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_spawn_protection_punishment_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_spawn_protection_punishment_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_spawn_protection_punishment_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_spawn_protection_punishment_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_spawn_protection_punishment_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_spawn_protection_punishment_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_spawn_protection_punishment_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_spawn_protection_punishment_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_spawn_protection_punishment_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_spawn_protection_punishment_time_war _null"
  
#define SETA_SCR_ANTI_CAMPING_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_camping_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_camping_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_camping_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_camping_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_camping_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_camping_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_camping_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_camping_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_camping_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_camping_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_camping_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_camping_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_camping_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_camping_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_camping_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_camping_enable_war _null"
  
#define SETA_SCR_ANTI_CAMPING_SHOW \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_camping_show_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_camping_show_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_camping_show_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_camping_show_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_camping_show_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_camping_show_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_camping_show_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_camping_show_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_camping_show_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_camping_show_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_camping_show_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_camping_show_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_camping_show_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_camping_show_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_camping_show_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_camping_show_war _null"
  
#define SETA_SCR_ANTI_CAMPING_MESSAGE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_camping_message_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_camping_message_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_camping_message_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_camping_message_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_camping_message_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_camping_message_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_camping_message_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_camping_message_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_camping_message_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_camping_message_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_camping_message_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_camping_message_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_camping_message_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_camping_message_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_camping_message_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_camping_message_war _null"
  
#define SETA_SCR_ANTI_CAMPING_DISTANCE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_camping_distance_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_camping_distance_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_camping_distance_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_camping_distance_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_camping_distance_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_camping_distance_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_camping_distance_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_camping_distance_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_camping_distance_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_camping_distance_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_camping_distance_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_camping_distance_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_camping_distance_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_camping_distance_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_camping_distance_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_camping_distance_war _null"
  
#define SETA_SCR_ANTI_CAMPING_TIME \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_camping_time_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_camping_time_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_camping_time_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_camping_time_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_camping_time_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_camping_time_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_camping_time_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_camping_time_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_camping_time_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_camping_time_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_camping_time_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_camping_time_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_camping_time_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_camping_time_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_camping_time_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_camping_time_war _null"
  
#define SETA_SCR_ANTI_BUNNY_HOPPING_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_bunny_hopping_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_bunny_hopping_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_bunny_hopping_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_bunny_hopping_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_bunny_hopping_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_bunny_hopping_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_bunny_hopping_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_bunny_hopping_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_bunny_hopping_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_bunny_hopping_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_bunny_hopping_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_bunny_hopping_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_bunny_hopping_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_bunny_hopping_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_bunny_hopping_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_bunny_hopping_enable_war _null"
  
#define SETA_SCR_ANTI_DOLPHIN_DIVE_ENABLE \
  execOnDvarStringValue menu_cfg_gt ass "seta scr_anti_dolphin_dive_enable_ass _null" \
  execOnDvarStringValue menu_cfg_gt bel "seta scr_anti_dolphin_dive_enable_bel _null" \
  execOnDvarStringValue menu_cfg_gt ch "seta scr_anti_dolphin_dive_enable_ch _null" \
  execOnDvarStringValue menu_cfg_gt ctf "seta scr_anti_dolphin_dive_enable_ctf _null" \
  execOnDvarStringValue menu_cfg_gt dm "seta scr_anti_dolphin_dive_enable_dm _null" \
  execOnDvarStringValue menu_cfg_gt ftag "seta scr_anti_dolphin_dive_enable_ftag _null" \
  execOnDvarStringValue menu_cfg_gt gg "seta scr_anti_dolphin_dive_enable_gg _null" \
  execOnDvarStringValue menu_cfg_gt gr "seta scr_anti_dolphin_dive_enable_gr _null" \
  execOnDvarStringValue menu_cfg_gt koth "seta scr_anti_dolphin_dive_enable_koth _null" \
  execOnDvarStringValue menu_cfg_gt oitc "seta scr_anti_dolphin_dive_enable_oitc _null" \
  execOnDvarStringValue menu_cfg_gt re "seta scr_anti_dolphin_dive_enable_re _null" \
  execOnDvarStringValue menu_cfg_gt sab "seta scr_anti_dolphin_dive_enable_sab _null" \
  execOnDvarStringValue menu_cfg_gt sd "seta scr_anti_dolphin_dive_enable_sd _null" \
  execOnDvarStringValue menu_cfg_gt ss "seta scr_anti_dolphin_dive_enable_ss _null" \
  execOnDvarStringValue menu_cfg_gt tgr "seta scr_anti_dolphin_dive_enable_tgr _null" \
  execOnDvarStringValue menu_cfg_gt war "seta scr_anti_dolphin_dive_enable_war _null"