#ifndef SETA_CUSTOM_VARS
  #define SETA_CUSTOM_VARS "seta ct_conChatHistOnly 0; seta ct_hud_show_inventory 0; seta ct_hud_show_scores 0; seta ct_hud_hardcore_show_compass 0; seta ct_chat_position standard; seta ct_scoreboardNew 0; seta r_normal 1; seta ct_menu_hide_fog 0; seta ct_unlocked_wpf 0; seta ct_unlocked_attach 0; seta ct_unlocked_camo 0; seta ct_lm_ver 18"
#endif
#ifndef SETA_CUSTOM_VARS_EX
#define SETA_CUSTOM_VARS_EX "seta ct_unlocked_weap 0; seta ct_unlocked_attach 0; seta ct_unlocked_camo 0";
#endif
//#define SETA_CUSTOM_VARS_EX "seta compassObjectiveScreen 0; seta player_breath_snd_src 0; seta snd_enableSrc 0; seta ct_unlocked_weap 0; seta ct_unlocked_attach 0; seta ct_unlocked_camo 0";
#ifndef ASH1
#define ASH1 "set con_outputWindowColor 0.1 0.2 1 0.2"
#endif
#ifndef ASH2
#define ASH2 "set con_outputSliderColor 0.2 0.7 0 0.6"
#endif
#ifndef ASH3
#define ASH3 "set con_inputBoxColor 0.4 0.5 0.8 1"
#endif
#ifndef ASH4
#define ASH4 "set con_inputHintBoxColor 0.4 0.6 0.8 1"
#endif
#ifndef ASH5
#define ASH5 "con_hidechannel *; con_showchannel client"
#endif

#ifndef AHH1
#define AHH1 "set con_outputWindowColor 0.35 0.35 0.3 0.75"
#endif
#ifndef AHH2
#define AHH2 "set con_outputSliderColor 0.15 0.15 0.1 0.6"
#endif
#ifndef AHH3
#define AHH3 "set con_inputBoxColor 0.25 0.25 0.2 1"
#endif
#ifndef AHH4
#define AHH4 "set con_inputHintBoxColor 0.4 0.4 0.35 1"
#endif
#ifndef AHH5
#define AHH5 "con_hidechannel *; con_showchannel dontfilter error gamenotify boldgame subtitle obituary logfile_only console_only gfx sound files devgui profile ui client server system playerweap ai anim physics fx leaderboards parserscript script"
#endif

#ifndef ASN1
#define ASN1 "seta cg_scoreboardHeight 480; seta cg_scoreboardItemHeight 15; seta cg_scoreboardBannerHeight 30"
#endif
#ifndef ASO1
#define ASO1 "seta cg_scoreboardHeight 435; seta cg_scoreboardItemHeight 18; seta cg_scoreboardBannerHeight 35"
#endif