//HQ
CHOICE_DVARFLOATLIST( 28, "@OW_HQ_MODE", scr_koth_kothmode, { "COD4" 0 "WW/MW2" 1 }, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_HQ_AUTODESTROY_TIME", scr_koth_autodestroytime, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_HQ_CAPTURE_TIME", scr_koth_capturetime, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_HQ_DELAY_PLAYER", scr_koth_delayPlayer, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_HQ_DESTROY_TIME", scr_koth_destroytime, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_HQ_SPAWN_TIME", scr_koth_spawntime, 3, ; )
CHOICE_DVARYESNO( 28, "@OW_FLASH_ON_DESTROY", scr_koth_flash_on_destroy, ; )