//DM

CHOICE_DVAREDIT_NUMERIC( 28, "@OW_NUMBER_OF_LIVES", scr_dm_numlives, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_PLAYER_RESPAWN_DELAY", scr_dm_playerrespawndelay, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_ROUNDLIMIT", scr_dm_roundlimit, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_SCORELIMIT", scr_dm_scorelimit, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_TIMELIMIT", scr_dm_timelimit, 5, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_ROUND_SWITCH", scr_war_roundswitch, 3, ; )
CHOICE_DVAREDIT_NUMERIC( 28, "@OW_WAVE_RESPAWN_DELAY", scr_war_waverespawndelay, 3, ; )
CHOICE_DVARYESNO( 28, "@OW_FORCE_START_SPAWNS", scr_war_forcestartspawns, ; )
CHOICE_DVARYESNO( 28, "@OW_TEAM_BALANCE_EOR", scr_war_teambalanceendofround, ; )